"""Add retail sentiment features to ticker_features_daily

Revision ID: 1e60a269304c
Revises: 52a296d14485
Create Date: 2025-08-16 23:11:53.613879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e60a269304c'
down_revision: Union[str, None] = '52a296d14485'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticker_features_daily', sa.Column('wsb_sentiment_3d', sa.Numeric(precision=5, scale=3), nullable=True))
    op.add_column('ticker_features_daily', sa.Column('wsb_sentiment_7d', sa.Numeric(precision=5, scale=3), nullable=True))
    op.add_column('ticker_features_daily', sa.Column('wsb_mention_count_7d', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('ticker_features_daily', sa.Column('wsb_engagement_score', sa.Numeric(precision=5, scale=3), nullable=True))
    op.add_column('ticker_features_daily', sa.Column('retail_buzz_score', sa.Numeric(precision=5, scale=3), nullable=True))
    op.add_column('ticker_features_daily', sa.Column('meme_stock_indicator', sa.Numeric(precision=5, scale=3), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticker_features_daily', 'meme_stock_indicator')
    op.drop_column('ticker_features_daily', 'retail_buzz_score')
    op.drop_column('ticker_features_daily', 'wsb_engagement_score')
    op.drop_column('ticker_features_daily', 'wsb_mention_count_7d')
    op.drop_column('ticker_features_daily', 'wsb_sentiment_7d')
    op.drop_column('ticker_features_daily', 'wsb_sentiment_3d')
    # ### end Alembic commands ###
