"""Initial schema migration

Revision ID: 52a296d14485
Revises: 
Create Date: 2025-08-16 21:48:18.707425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52a296d14485'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('articles_hash_sha256_idx', table_name='articles', postgresql_where='(hash_sha256 IS NOT NULL)')
    op.create_unique_constraint(None, 'articles', ['hash_sha256'])
    op.alter_column('doc_embedding', 'model',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'text-embedding-ada-002'::text"))
    op.drop_constraint('doc_embedding_doc_id_fkey', 'doc_embedding', type_='foreignkey')
    op.create_foreign_key(None, 'doc_embedding', 'articles', ['doc_id'], ['id'])
    op.alter_column('doc_entity', 'ticker',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('doc_entity', 'method',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('doc_entity', 'confidence',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=3, scale=2),
               existing_nullable=False)
    op.drop_index('doc_entity_doc_id_idx', table_name='doc_entity')
    op.drop_index('doc_entity_ticker_confidence_idx', table_name='doc_entity')
    op.drop_constraint('doc_entity_doc_id_fkey', 'doc_entity', type_='foreignkey')
    op.create_foreign_key(None, 'doc_entity', 'articles', ['doc_id'], ['id'])
    op.drop_index('recommendations_feature_ref_idx', table_name='recommendations', postgresql_where='(feature_date IS NOT NULL)')
    op.alter_column('ticker_features_daily', 'ticker',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('ticker_features_daily', 'feature_version',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'v1.0.0'::text"))
    op.alter_column('ticker_features_daily', 'sent_mean_3d',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=5, scale=3),
               existing_nullable=True)
    op.alter_column('ticker_features_daily', 'sent_mean_7d',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=5, scale=3),
               existing_nullable=True)
    op.alter_column('ticker_features_daily', 'sent_mean_10d',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=5, scale=3),
               existing_nullable=True)
    op.alter_column('ticker_features_daily', 'sent_shock',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=5, scale=3),
               existing_nullable=True)
    op.alter_column('ticker_features_daily', 'sent_volume_weighted',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=5, scale=3),
               existing_nullable=True)
    op.alter_column('ticker_features_daily', 'ret_1d',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=8, scale=6),
               existing_nullable=True)
    op.alter_column('ticker_features_daily', 'ret_5d',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=8, scale=6),
               existing_nullable=True)
    op.alter_column('ticker_features_daily', 'ret_20d',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=8, scale=6),
               existing_nullable=True)
    op.alter_column('ticker_features_daily', 'vol_z',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=5, scale=3),
               existing_nullable=True)
    op.alter_column('ticker_features_daily', 'momentum_14d',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=8, scale=6),
               existing_nullable=True)
    op.alter_column('ticker_features_daily', 'earnings_d',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('ticker_features_daily', 'conflict_score',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=5, scale=3),
               existing_nullable=True)
    op.alter_column('ticker_features_daily', 'novelty_mean_3d',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=5, scale=3),
               existing_nullable=True)
    op.alter_column('ticker_features_daily', 'article_count_7d',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index('ticker_features_daily_date_idx', table_name='ticker_features_daily')
    op.drop_index('ticker_features_daily_ticker_date_idx', table_name='ticker_features_daily')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ticker_features_daily_ticker_date_idx', 'ticker_features_daily', ['ticker', sa.text('date DESC')], unique=False)
    op.create_index('ticker_features_daily_date_idx', 'ticker_features_daily', [sa.text('date DESC')], unique=False)
    op.alter_column('ticker_features_daily', 'article_count_7d',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('ticker_features_daily', 'novelty_mean_3d',
               existing_type=sa.Numeric(precision=5, scale=3),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('ticker_features_daily', 'conflict_score',
               existing_type=sa.Numeric(precision=5, scale=3),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('ticker_features_daily', 'earnings_d',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=True)
    op.alter_column('ticker_features_daily', 'momentum_14d',
               existing_type=sa.Numeric(precision=8, scale=6),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('ticker_features_daily', 'vol_z',
               existing_type=sa.Numeric(precision=5, scale=3),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('ticker_features_daily', 'ret_20d',
               existing_type=sa.Numeric(precision=8, scale=6),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('ticker_features_daily', 'ret_5d',
               existing_type=sa.Numeric(precision=8, scale=6),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('ticker_features_daily', 'ret_1d',
               existing_type=sa.Numeric(precision=8, scale=6),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('ticker_features_daily', 'sent_volume_weighted',
               existing_type=sa.Numeric(precision=5, scale=3),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('ticker_features_daily', 'sent_shock',
               existing_type=sa.Numeric(precision=5, scale=3),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('ticker_features_daily', 'sent_mean_10d',
               existing_type=sa.Numeric(precision=5, scale=3),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('ticker_features_daily', 'sent_mean_7d',
               existing_type=sa.Numeric(precision=5, scale=3),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('ticker_features_daily', 'sent_mean_3d',
               existing_type=sa.Numeric(precision=5, scale=3),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('ticker_features_daily', 'feature_version',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'v1.0.0'::text"))
    op.alter_column('ticker_features_daily', 'ticker',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_index('recommendations_feature_ref_idx', 'recommendations', ['stock_id', 'feature_date', 'feature_version'], unique=False, postgresql_where='(feature_date IS NOT NULL)')
    op.drop_constraint(None, 'doc_entity', type_='foreignkey')
    op.create_foreign_key('doc_entity_doc_id_fkey', 'doc_entity', 'articles', ['doc_id'], ['id'], ondelete='CASCADE')
    op.create_index('doc_entity_ticker_confidence_idx', 'doc_entity', ['ticker', sa.text('confidence DESC')], unique=False)
    op.create_index('doc_entity_doc_id_idx', 'doc_entity', ['doc_id'], unique=False)
    op.alter_column('doc_entity', 'confidence',
               existing_type=sa.Numeric(precision=3, scale=2),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('doc_entity', 'method',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('doc_entity', 'ticker',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'doc_embedding', type_='foreignkey')
    op.create_foreign_key('doc_embedding_doc_id_fkey', 'doc_embedding', 'articles', ['doc_id'], ['id'], ondelete='CASCADE')
    op.alter_column('doc_embedding', 'model',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'text-embedding-ada-002'::text"))
    op.drop_constraint(None, 'articles', type_='unique')
    op.create_index('articles_hash_sha256_idx', 'articles', ['hash_sha256'], unique=False, postgresql_where='(hash_sha256 IS NOT NULL)')
    # ### end Alembic commands ###
