"""Add signals and alerts tables

Revision ID: c2526350b48a
Revises: 1e60a269304c
Create Date: 2025-08-16 23:24:16.809773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c2526350b48a'
down_revision: Union[str, None] = '1e60a269304c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_subscriptions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('alert_types', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('delivery_methods', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('thresholds', sa.JSON(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_subscriptions_user_id'), 'alert_subscriptions', ['user_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('alert_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signal_id', sa.UUID(), nullable=True),
    sa.Column('alert_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_ticker'), 'alerts', ['ticker'], unique=False)
    op.add_column('signals', sa.Column('ticker', sa.String(), nullable=False))
    op.add_column('signals', sa.Column('strength', sa.Numeric(precision=5, scale=3), nullable=False))
    op.add_column('signals', sa.Column('confidence', sa.Numeric(precision=5, scale=3), nullable=False))
    op.add_column('signals', sa.Column('direction', sa.String(), nullable=False))
    op.add_column('signals', sa.Column('timeframe', sa.String(), nullable=False))
    op.add_column('signals', sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('signals', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('signals', sa.Column('signal_metadata', sa.JSON(), nullable=True))
    op.add_column('signals', sa.Column('features_snapshot', sa.JSON(), nullable=True))
    op.add_column('signals', sa.Column('model_version', sa.String(), nullable=False))
    op.alter_column('signals', 'signal_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index('ix_signals_signal_type', table_name='signals')
    op.drop_index('ix_signals_stock_id', table_name='signals')
    op.create_index(op.f('ix_signals_ticker'), 'signals', ['ticker'], unique=False)
    op.drop_constraint('signals_stock_id_fkey', 'signals', type_='foreignkey')
    op.drop_column('signals', 'computed_at')
    op.drop_column('signals', 'details')
    op.drop_column('signals', 'value')
    op.drop_column('signals', 'stock_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signals', sa.Column('stock_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('signals', sa.Column('value', sa.NUMERIC(precision=18, scale=6), autoincrement=False, nullable=False))
    op.add_column('signals', sa.Column('details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('signals', sa.Column('computed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.create_foreign_key('signals_stock_id_fkey', 'signals', 'stocks', ['stock_id'], ['id'])
    op.drop_index(op.f('ix_signals_ticker'), table_name='signals')
    op.create_index('ix_signals_stock_id', 'signals', ['stock_id'], unique=False)
    op.create_index('ix_signals_signal_type', 'signals', ['signal_type'], unique=False)
    op.alter_column('signals', 'signal_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('signals', 'model_version')
    op.drop_column('signals', 'features_snapshot')
    op.drop_column('signals', 'signal_metadata')
    op.drop_column('signals', 'expires_at')
    op.drop_column('signals', 'generated_at')
    op.drop_column('signals', 'timeframe')
    op.drop_column('signals', 'direction')
    op.drop_column('signals', 'confidence')
    op.drop_column('signals', 'strength')
    op.drop_column('signals', 'ticker')
    op.drop_index(op.f('ix_alerts_ticker'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_alert_subscriptions_user_id'), table_name='alert_subscriptions')
    op.drop_table('alert_subscriptions')
    # ### end Alembic commands ###
